fix: building static html pages #95313
> failed Building static HTML for pages - 1.301s
>
> ERROR #95313
> Building static HTML failed for path "/blog/2019-09-27/inspect-hoverable-event/"
> See our docs page for more info on this error: https://gatsby.dev/debug-html
>   Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full messa  ge or use the non-minified dev environment for full errors and additional helpful warnings.

Even though the original gatsby-ssr was all cjs, this was still throwing an error.

Converting to es modules resolves the error.